<div class="absolutemain">
	<div class="main">
		<h5 class="marginheader">Företagsfakta</h5>
	<br/>	
			<font class="TioPix">		
				<b>Oqtopus</b> är en marknadsplats som hjälper annonsköpare och annonssäljare att hitta varandra. 
				Den tekniska plattform som  vi tillhandahåller minskar transaktionskostnaderna för alla parter 
				vilket i sin tur skapar möjligheter för fler företag att köpa reklam.
		
	<br/><br/>	<b>För medier</b> och andra annonssäljare erbjuder vi exponering av annonser, 
				kreditupplysning av annonsköpare och administrationsverktyg för 
				att hitta och bearbeta nya köpare.
		
	<br/><br/>	<b>För annonsköpare</b> erbjuder vi ett stort utbud av annonser och möjligheten att göra snabba köp, helt gratis!
	
	<br/><br/>	</font>
	</div>
	
	<div class="main">
		<h5 class="marginheader">Historia</h5> 
	<br/>
			<font class="TioPix">		
				Företagets grundare är <b>Bijan Fahimi</b>, <b>Eli Kaufman</b> och <b>Siavosh Zarrasvand</b>.<br/><br/>
				<b>Oqtopus.se</b> lanserades under oktober 2006.				
			</font>
	</div>
</div>

<div class="vanstertext">
	<h5 class="marginheader">Kontakt</h5>
	<br/>
			<font class="TioPix">
				<b>Oqtopus</b>
	<br/>		S:t Eriksgatan 63
	<br/>		Box 8069 <br/>
	<br/>		104 20 Stockholm
	<br><br>	<b>Växel:</b> 08-545 285 80
	<br/>		<b>Fax:</b> 08-545 285 81
	<br/>		<b>Mejl:</b> <a href="mailto:support@oqtopus.se">support@oqtopus.se</a>
			</font>
</div>
