<div class="absolutemain">
<div class="main">
<h5 class="marginheader">Kategori: <?php $this->slblBrowsing->Render() ?></h5><br/>
<?php $this->dtgData->Render(); ?>
</div>

</div>

<div class="vanstertext">
<h5 class="marginheader">Kontakt</h5><font class="TioPix">
<br/>

<font class="TioPix">
<b>Oqtopus</b><br>
S:t Eriksgatan 63<br/>
Box 8069 <br/>
104 20 Stockholm<br><br>

<b>Växel:</b> 08-545 285 80<br/>
<b>Fax:</b> 08-545 285 81<br/>
<b>Mejl:</b> <a href="mailto:support@oqtopus.se">support@oqtopus.se</a>
</font>

</div>