<div class="vanstertext">
<h5 class="marginheader">Kontakt</h5><font class="TioPix">
<br/>

<font class="TioPix">
<b>Oqtopus</b><br>
S:t Eriksgatan 63<br/>
Box 8069 <br/>
104 20 Stockholm<br><br>

<b>Växel:</b> 08-545 285 80<br/>
<b>Fax:</b> 08-545 285 81<br/>
<b>Mejl:</b> <a href="mailto:support@oqtopus.se">support@oqtopus.se</a>
</font>
</div>



<div class="absolutemain">
<div class="main">

<h5 class="marginheader">Mervärden för köpare</h5>
<br/>
<font class="TioPix"><b>
Varför?</b><br/>

<br/>    - Hitta ett stort utbud av både lokal och nationell media
<br/>    - Jämföra priser och målgrupp
<br/>	 - Lägg bud på befintliga annonser och förhandla om priset enkelt och effektivt
<br/>    - Hitta nya vägar att nå just er kundkrets
<br/>    - Få erbjudanden om sistaminutenannonser och kampanjer
<br/>    - Göra snabba och enkla köp helt kostnadsfritt

<br/><br/><b>Hur?</b>

<br/><br/>    - Logga in på kontot och gör en sökning på en annons
<br/>    - Lägg bud på den annons ni vill ha
<br/>    - Säljaren godkänner budet
<br/>    - Klart!<br /><br />
Registrering för köpare öppnar väldigt snart. För att vara säker på att du inte missar det,<br />
gå till <a href="<?php echo Navigation::CreateUrl('PressForm') ?>">Press</a> och prenumerera på våra nyhetsbrev.

</font>

</div>

</div>