<div class="vanstertext">
	<h5 class="marginheader">Kom igång</h5>
		<br />
			
			<font class="TioPix"><b>Hej</b> och välkommen som <b>köpare</b> på Oqtopus. <br><br>	
			Bästa sättet att komma igång är att läsa våra 
			<b><a href="<?php print Navigation::CreateUrl('BuyersNewsForm');?>">demofiler</a></b> 
			för säljare. </font><br/><br/>

<h5 class="marginheader">Kontakt</h5><font class="TioPix">
<br/>

<font class="TioPix">
<b>Oqtopus</b><br>
S:t Eriksgatan 63<br/>
Box 8069 <br>
104 20 Stockholm<br/><br/>

<b>Växel:</b> 08-545 285 80<br/>
<b>Fax:</b> 08-545 285 81<br/>
<b>Mejl:</b> <a href="mailto:support@oqtopus.se">support@oqtopus.se</a>
</font>

</div>


<div class="absolutemain">
<div class="main">

<h5 class="marginheader">Senaste nytt</h5><br/>

<b>Länk: </b><a class="hover" href="<?php print Navigation::CreateUrl('PressForm');?>">Nyheter</a><br/>
<b>Länk: </b><a class="hover" href="<?php print Navigation::CreateUrl('BuyersBidsForm');?>"><?php $this->lblAnsweredBids->Render(); ?>&nbsp;besvarade bud sedan senaste inloggningen</a><br/>
<b>Länk: </b><a class="hover" href="<?php print Navigation::CreateUrl('BuyersNetworksForm');?>"><?php $this->lblOffers->Render() ?>&nbsp;exklusivt tillgängliga kampanjerbjudanden</a><br/><br/>

</div>

</div>