<div class="vanstertext">
<h5 class="marginheader">Kontakt</h5>
<br/>

<font class="TioPix">
<b>Oqtopus</b><br>
S:t Eriksgatan 63<br/>
Box 8069 <br/>
104 20 Stockholm<br><br>

<b>Växel:</b> 08-545 285 80<br/>
<b>Fax:</b> 08-545 285 81<br/>
<b>Mejl:</b> <a href="mailto:support@oqtopus.se">support@oqtopus.se</a>
</font>

</div>



<div class="absolutemain">
	<div class="main">
		<h5 class="marginheader">Rola Brentlin</h5> 
			<br />
				<font class="TioPix">		
					Rola leder försäljningsarbetet. Kontakta henne för mer information om våra tjänster och erbjudanden. 
					<br/><br/>
					<b>Mejl:</b> <a href="mailto:rola.brentlin@oqtopus.se">rola.brentlin@oqtopus.se</a>
					<br/>
					<b>Telefon:</b> +46(0)737629890
					<br/><br/>
				</font>
	</div>

	<div class="main">
		<h5 class="marginheader">Siavosh Zarrasvand</h5> 
			<br />
				<font class="TioPix">		
					Siavosh kontaktas vid pressrelaterade frågor eller frågor 
					som rör Oqtopus operativa verksamhet, exempelvis samarbeten. 
					<br/><br/>
					<b>Mejl:</b> <a href="mailto:siavosh.zarrasvand@oqtopus.se">siavosh.zarrasvand@oqtopus.se</a>
					<br/>
					<b>Telefon:</b> +46(0)732638229
					<br/><br/>
				</font>
	</div>
	
</div>