<div class="vanstertext">
<h5 class="marginheader">Kontakt</h5>
<br/>

<font class="TioPix">
<b>Oqtopus</b><br>
S:t Eriksgatan 63<br/>
Box 8069 <br/>
104 20 Stockholm<br><br>

<b>Växel:</b> 08-545 285 80<br/>
<b>Fax:</b> 08-545 285 81<br/>
<b>Mejl:</b> <a href="mailto:support@oqtopus.se">support@oqtopus.se</a>
</font>

</div>



<div class="absolutemain">
<div class="main">

	<h5 class="marginheader">Säljande</h5> 
		<br />

<font class="TioPix">
	Inom kort kommer vi lista alla företag som säljer annonsutrymme på Oqtopus här.
</font>

</div>

<div class="main">

	<h5 class="marginheaderblue">Köpare</h5> 
<br />
<font class="TioPix">
	Inom kort kommer vi lista alla företag som köper annonsutrymme på Oqtopus här.
</font>
</div>


<div class="main">

	<h5 class="marginheader">Samarbetspartners</h5> 
<br />
<font class="TioPix">

	<a href="http://www.veritas.se" target="_blank">Veritas Communication AB</a><br></br>
</font>

</div>

</div>

