<div id="framsida"></div>
						<a href="<?php echo Navigation::CreateUrl('SellersValuesForm')  ?>">
							<div id="ruta1">
							<br />
								<h3 class="marginzero">Annonssäljare</h3>
								<font class="hoger"><ul>
									<li>Minska administrationen och försäljningskostnaderna</li><br/>
									<li>Nå nya annonsköpare</li><br/>
									<li>Sälj sistaminutenannonser och genomför riktade kampanjer</li>
									</ul>
								</font>
							</div>
						</a>
												
						<a href="<?php echo Navigation::CreateUrl('BuyersValuesForm') ?>">
							<div id="ruta2">
							<br />
								<h3 class="marginzero">Annonsköpare</h3>
								<font class="hoger"><ul>
									<li>Få en överblick över det totala annonsutbudet</li><br/>
									<li>Handla snabbt, säkert och billigt</li><br/>
									<li>Annonsera i  ickeexponerade utrymmen med liten kostnad</li>
									</ul>
								</font>
							</div>
						</a>
    					
						<a href="<?php echo Navigation::CreateUrl('MainForm') ?>">
							<div id="ruta3"><h3 class="marginzero">Så fungerar det</h3><i><h5>(Säljare)</h5></i></div></a>
  						
						<a href="<?php echo Navigation::CreateUrl('MainForm') ?>">
							<div id="ruta4"><h3 class="marginzero">Så fungerar det</h3><i><h5>(Köpare)</h5></i></div></a>
