<div class="vanstertext">
<h5 class="marginheader">Kontakt</h5>
<br/>

<font class="TioPix">
<b>Oqtopus</b><br>
S:t Eriksgatan 63<br/>
Box 8069 <br/>
104 20 Stockholm<br><br>

<b>Växel:</b> 08-545 285 80<br/>
<b>Fax:</b> 08-545 285 81<br/>
<b>Mejl:</b> <a href="mailto:support@oqtopus.se">support@oqtopus.se</a>
</font>

</div>


<div class="absolutemain">
	<div class="main">

		<h5 class="marginheader">Pressmeddelanden</h5> 
	<br />
	<font class="TioPix">
		För närvarande finns inga pressmeddelanden tillgängliga.
	</font>
	
	</div>

	<div class="main">
		<h5 class="marginheaderblue">Nyhetsbrev</h5> 
	<br />
	<font class="TioPix">
		För närvarande finns inga nyhetsbrev tillgängliga.
	</font>

	</div>

	<div class="main">

		<h5 class="marginheader">Artiklar</h5> 
	<br />
	<font class="TioPix">
		För närvarande finns inga artiklar tillgängliga.
	</font>

	</div>

	<div class="main">

	<h5 class="marginheaderblue">Prenumerera</h5> 
	<br />
	<table class="TioPix">
		<tr>
			<td class="tdPanelAd4"><?php	$this->chkOptions->RenderWithError();	?></td>
			<td class="tdPanelAd4"><?php	$this->txtSubscriptionEmail->RenderWithError(); ?></td>
			<td class="tdPanelAd4"><?php 	$this->btnDoSubscribe->Render();	?></td>
			<td></td>
			<td class="tdPanelAd4"><?php	$this->lblSubInfo->Render();	?></td>
		</tr>
	</table>		

</div>

</div>