<br />
<table class="TioPix">
	<tr>
		<td class="tdPanelAd5"><?php $this->lblSellerNumber->RenderWithName();?></td>
		<td class="tdPanelAd5"><?php $this->lblSellerContactAdress->RenderWithName();?></td>
		<td class="tdPanelAd5"><?php $this->pnlSellerDesc->RenderWithName();?></td>
	</tr>

	<tr>
		<td class="tdPanelAd5"><?php $this->lblSellerContactName->RenderWithName();?></td>
		<td class="tdPanelAd5"><?php $this->lblSellerContactPhone->RenderWithName();?></td>
		<td class="tdPanelAd5"><?php $this->lblSellerContactEmail->RenderWithName();?></td>
	</tr>

</table>