<div class="absolutenetwork">
<h5 class="marginheader">Vad är Kampanjnätverk?</h5>
<br />
<font class="TioPix">Som annonsör har du möjlighet att få anpassade <b>erbjudanden</b>. 
<br /><br />
Hitta de kampanjnätverk vars beskrivningar passar in på <b>ditt företag</b> och ansök.</font>
<br /><br />

<h5 class="marginheader">Kampanjnätverk</h5>
<br />


<table class="TioPix">
	<tr>
		<td class="tdAuto"><?php	$this->lbNetworks->RenderWithError();	?><?php	$this->btnApplyForNetwork->Render();	?></td>
	</tr>
	
	<tr>
		<td class="tdPanelAd1"><?php	$this->pnlNetworkDescription->Render();	?></td>
	</tr>
	
	<tr>
		<td class="tdPanelAd1"><?php	$this->lblNetworkInfo->Render();	?></td>
	</tr>
</table>

</div>