<div class="vanstertext">
<h5 class="marginheader">Prenumerera på sökningar</h5>
<br />
<font class="TioPix">På Oqtopus <b>prenume- rerar</b> du på dina sökningar och får ett mejl
varje gång ett nytt matchande objekt tillkommer.<br/><br/> 
Om du inte vill prenumerera måste du <b>bocka av</b> kryssrutan innan du genomför sökningen.
</font>
<br /><br />

<h5 class="marginheader">Disclaimer</h5>
<br />
<font class="TioPix">Sökningar sker utifrån den information som säljare <b>själva</b> anger.<br /><br />
Oqtopus <b>scannar</b> ständigt av utbudet för att hålla missvisande information borta. <br/><br/>

För att påpeka vilseledande information från en säljare, 
kontakta <b><a href="mailto:support@oqtopus.se">supporten</a>.</font></b><br /><br />

<h5 class="marginheader">Kontakt</h5>
<br/>

<font class="TioPix">
<b>Oqtopus</b><br>
S:t Eriksgatan 63<br/>
Box 8069 <br/>
104 20 Stockholm<br><br>

<b>Växel:</b> 08-545 285 80<br/>
<b>Fax:</b> 08-545 285 81<br/>
<b>Mejl:</b> <a href="mailto:support@oqtopus.se">support@oqtopus.se</a>
</font>

</div>


<div class="absolutemain">
<?php $this->pnlSearch->Render();  ?><?php $this->pnlResults->Render(); ?>
</div>

