<div class="absolutemain">
<div class="main">
<h5 class="marginheader">Inställningar</h5>

		<b>Här kan du ändra informationen om ert företag och om kontaktpersonen.</b><br/><br/>
 		Du kan även välja om du vill ha ett mejl varje gång någon lägger ett bud på någon av dina annonser <br/>
 		 eller ansöker till något av dina kampanjnätverk.

		<img src="/adds/installningar.png" class="demo">

</div>

</div>