
<div class="absolutemain">
	<div class="main">
	<h5 class="marginheader">Annonser</h5>

		<font class="TioPix"><i>Administrering av annonser</i>
		<br/><br/>

	<div class="imgdemo"><img src="/adds/annonser1.png" class="demo"></div>

		<b>Nytt erbjudande</b> - Klickar du på Nytt erbjudande kommer du till sidan där du ska lägga
		upp tillfälliga kampanjerbjudanden.</font>
		<br/>



		<br /><br/>
		
		<font class="TioPix">
		<b>Namn</b> - Här fyller du i vad du vill kalla annonsen, om du väljer ett namn som förtydligar vad för typ av <br/>
		  annons det gäller är chansen större att du får ett bud, exempelvis Helsida, 1: a sida, Headbanner osv.<br/><br/>

		<b>Kategori</b> - Här väljer du vilken mediekategori som annonsutrymmet gäller. <br/><br/>

		<b>Beskrivning</b> - Beskriva annonsen så utförligt du kan för köparen. Ju mer detaljerat du skriver desto <br/>
		mer ökar du dina chanser att få sålt annonsen.<br/><br/>


		<b>Publiceringsdatum</b> - Detta är en av två punkter som skiljer annonserbjudanden från vanliga annonser. <br/>
		Eftersom vanliga annonser endast förväntas vara fasta moduler för vad en annons kostar i din<br/> 
		publikation, medan erbjudanden är annonser som du lägger upp med kort varsel, måste du angen<br/> 
		publiceringsdatum och ett deadline då fler bud inte tas emot<br/><br/>


		<b>Räckvidd</b> - Räckvidd är svårmätt och för rättvisans skull kommer vi på Oqtopus hellre fälla än<br/>
		fria om vi misstänker felaktiga siffror. Observera därför att om ni inte har riktiga räckviddsiffror<br/> 
		får ni endast använda er av antal prenumeranter.<br/><br/>

		<b>Kampanjnätverk</b> - Detta är den andra punkten som skiljer annonserbjudanden från vanliga annonser.<br/>
		För att kunna hantera vilka som ska se dina erbjudanden kan du skapa kampanjnäntverk som kan få åtkosmt<br/>
		till dina erbjudanden. Du kan då välja vilka som ska få se dina erbjudanden och vilka som inte ska få se dem. <br/>
		(Läs mer om kampanjnätverk under fliken kampanjnätverk)<br/><br/>

		<i>Under målgruppspecifikation ska du fylla i ålder på dina läsare, lönegrupp osv. Fyll i så utförligt som möjligt så att<br/>
		kunden får en klar bild av vilka kunder det är han/hon når. I rutan ”nyckelord” ska du fylla i de ord som beskriver er <br/>
		tidning bäst. När en kund söker annonser kan de använda sig av nyckelord och då få en matchning med just er.</i><br/><br/>

		När du har fyllt i allt klickar du på ok och annonsen kommer upp.</font>
		<br/><br/>

<img src="/adds/annonser2.png" class="demo">

</div>

</div>
