

<div class="absolutemain">
<div class="main">
<h5 class="marginheader">Bud</h5>

		<b>Här ser du alla lagda bud på dina annonser samt budhistorik</b><br/><br/>
		Du kan se alla bud som har lagts på dina annonser samt acceptera eller avböja dem. Glöm inte att titta <br/>
		på kolumen <i>Kreditvärdig</i> när du granskar ett bud. "Ja" betyder att köpare inte har en betalningsanmärkan.<br> 
		När du har accepterat ett bud kan du använda ett mejlformulär längs ner på sidan för att kontakta köparen. 
<br/>
		<td><img src="/adds/bud.png" class="demo">
		<td class="tdPanelAd4"></td>

</div>

</div>