<?php $this->pnlC->Render() ?>

<div class="vanstertext">

<h5 class="marginheader">Demo för säljare</h5>

	<ul class="demoform">
		<li><a href="<?php echo Navigation::CreateUrl('SellersDemoForm') ?>">Nyhetssida</a></li>
		<li><a href="<?php echo Navigation::CreateUrl('SellersDemoForm&arg1=2') ?>">Annonser</a></li>
		<li><a href="<?php echo Navigation::CreateUrl('SellersDemoForm&arg1=3') ?>">Lägga upp annoner</a></li>
		<li><a href="<?php echo Navigation::CreateUrl('SellersDemoForm&arg1=4') ?>">Erbjudanden</a></li>
		<li><a href="<?php echo Navigation::CreateUrl('SellersDemoForm&arg1=5') ?>">Bud och kredit- upplysning</a></li>
		<li><a href="<?php echo Navigation::CreateUrl('SellersDemoForm&arg1=6') ?>">Kampanjnätverk</a></li>
		<li><a href="<?php echo Navigation::CreateUrl('SellersDemoForm&arg1=7') ?>">Sökmotorn</a></li>
		<li><a href="<?php echo Navigation::CreateUrl('SellersDemoForm&arg1=8') ?>">Mer säkerhet</a></li>
	 </ul>					

</div>
