
<div class="absolutemain">
<div class="main">
<h5 class="marginheader">Kampanjnätverk</h5>
		<b>Här syns företag som på förhand har ansökt om att få vara med och ta del av dina erbjudanden.</b><br/><br/>
 		De kunder som ansöker är extra intresserade av att annonsera i just din tidning och vill ha erbjudanden från <br/>
 		just dig. Du kan här godkänna eller avslå deras ansökan.
		<img src="/adds/kampanj.png" class="demo">
		
	</div>
</div>