<div class="vanstertext">
<h5 class="marginheader">Kontakt</h5><font class="TioPix">
<br/>

<font class="TioPix">
<b>Oqtopus</b><br>
S:t Eriksgatan 63<br/>
Box 8069 <br/>
104 20 Stockholm<br><br>

<b>Växel:</b> 08-545 285 80<br/>
<b>Fax:</b> 08-545 285 81<br/>
<b>Mejl:</b> <a href="mailto:support@oqtopus.se">support@oqtopus.se</a>
</font>

</div>


<div class="absolutemain">

<div class="main">
<h5 class="marginheader">Mervärden för säljare</h5>
<br/>
<font class="TioPix"><b>
Varför?</b>
<br/>
<br/>-	Minska kostnaderna för annonsförsäljning
<br/>-	Nå ut till nya kundgrupper som annars är svåra att nå
<br/>-	Få en gratis kreditupplysning på alla potentiella kunder
<br/>-	Få en möjlighet att skapa kampanjnätverk med just dina potentiella kunder
<br/>-	Kostnadsfri marknadsföring av era annonsplatser!

<br/><br/><b>Hur?</b>

<br/><br/>-	Ni lägger upp era annonser och erbjudande
<br/>-	Vi marknadsför dem åt er
<br/>-	En kund lägger bud på er annons
<br/>-	Vi godkänner kundens kreditvärde
<br/>-	Du godkänner budet och köpet är genomfört!
<br/>-	Vi tar endast 3 % av annonspriset  

<br/><br/><i>Exempel, du säljer en annons för 10 000: - för det tar vi endast 300: - Detta är vad en säljare hade kostat dig i timmen.</i><br /><br />
För att direkt registrera dig, klicka <a href="<?php echo Navigation::CreateUrl('SellersRegisterForm') ?>">HÄR</a>. Det är självklart helt gratis.
</font>

</div>

</div>