<div class="vanstertext">
<h5 class="marginheader">Mer om kampanjnätverk..</h5>
<br/>
<font class="TioPix">
<b>Kampanjnätverken</b> används till att genomföra 
riktade kampanjer till specifika företagsgrupper. <br/><br/>
Målet är att minska <b>kostnaden</b> när du letar nya kundgrupper.
</font>
<br/><br/>

<h5 class="marginheader">Kontakt</h5>
<br/>

<font class="TioPix">
<b>Oqtopus</b><br>
S:t Eriksgatan 63<br/>
Box 8069 <br/>
104 20 Stockholm<br><br>

<b>Växel:</b> 08-545 285 80<br/>
<b>Fax:</b> 08-545 285 81<br/>
<b>Mejl:</b> <a href="mailto:support@oqtopus.se">support@oqtopus.se</a>
</font>

</div>

<div class="absolutemain">
<div class="main">
<h5 class="marginheader">Kampanjnätverk</h5>

<br />
	
	<?php	$this->dtgNetworks->Render();	?>
<br />
<div class="btnAdd"><?php	$this->btnAdd->Render();	?></div>
<br />

<?php	$this->objNetworkPanel->Render();	?>

</div>

<div class="main">
<h5 class="marginheader">Ansökningar</h5>
<br />
	<td><?php	$this->dtgApplications->Render();	?></td>

</div>

</div>