

<div class="absolutemain">
	<div class="main">
		<h5 class="marginheader">Konto</h5>
			<font class="TioPix"><i>Nyheter - Sammanfattande sida</i></font>
	
	<br/>	<div class="imgdemo"><img src="/adds/konto.png" class="demo"></div>
	
	<br/>	<font class="TioPix">
				Fliken <b>Nyheter</b> sammanfattar relevanta händelser sedan kontot användes senast. 
				Exempelvis nya bud som kommit och hur mycket saldot ligger på.
			</font>
	<br/><br/><br/><br/><br/>
	</div>
</div>

