<div class="vanstertext">
<h5 class="marginheader">Kreditupplysningar</h5>
<font class="TioPix">
<br/>
Oqtopus genomför en <b>kreditupplysning</b> på alla registrerade köpare.<br/><br/>
Upplysningen förnyas var tionde arbetsdag.
</font>
<br/><br/>


<h5 class="marginheader">Kontakt</h5>
<br/>

<font class="TioPix">
<b>Oqtopus</b><br>
S:t Eriksgatan 63<br/>
Box 8069 <br/>
104 20 Stockholm<br><br>

<b>Växel:</b> 08-545 285 80<br/>
<b>Fax:</b> 08-545 285 81<br/>
<b>Mejl:</b> <a href="mailto:support@oqtopus.se">support@oqtopus.se</a>
</font>

</div>

<div class="absolutemain">
<div class="main">

<h5 class="marginheader">Senaste bud</h5>

<br />

<?php echo('<br>'); $this->dtgNewBids->Render(); echo('<br>'); ?>
<br />
</div>

<div class="main">

			<h5 class="marginheader">Budhistorik</h5> 
			
			<?php echo('<br>');	$this->dtgOldBids->Render();	echo('<br>');	?>


<?php $this->pnlContact->Render() ?>
</div>


</div>


<br /><br /><br /><br /><br /><br /><br /><br /><br /><br />